# Site settings
title: srbcheema1
description: A blog by an overthinker
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Srb Cheema
user_description: A curious guy who is in love with problems. I am student of Computer Science, enthusiastic about learning new algorithms and technologies related to computer science. Those who know me say me a lazy programmer as I am quite lazy at repeating the stuff, you I am habitual of writing down script to automate almost everthing that I feel like boring in repeating everytime. I am a compitive programmer as well as an Open Source lover.

user_title: Programmer | Developer | Overthinker
email: srbcheema1@gmail.com
twitter_username: srbcheema1
github_username:  srbcheema1
gplus_username:  srbcheema1

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
